INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES
(NULL, 'manage_users', 'users', 'users', 'Users', 'Users', NULL, '/users', 3, 1, 2, 0),
(NULL, 'manage_users', 'user_roles', 'user_roles', 'User Roles', 'User Roles', NULL, '/user_roles', 3, 2, 2, 0),
(NULL, 'manage_users', 'manage_users', 'manage_users', 'Manage Users and Roles', 'Manage Users', 'fa-group', 'manage_users', NULL, 2, 1, 0),
(NULL, 'home', 'dashboard', '', 'Dashboard', 'Dashboard', 'fa-dashboard', NULL, NULL, 1, 1, 0),
(NULL, 'maintenance', 'maintenance', 'maintenance', 'Maintenance', 'Maintenance', 'fa-cogs', 'maintenance', NULL, 3, 1, 0),
(NULL, 'maintenance', 'general_maintenance', 'general', 'General', 'General Maintenance', NULL, '/general', 5, 1, 2, 0);
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'cost_center', 'cost_center', 'Cost Center', 'Cost Center', NULL, '/cost_center', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'ac_mapping', 'ac_mapping', 'Item Master Account Code Mapping', 'Item Master Account Code Mapping', NULL, '/ac_mapping', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'aop_targets', 'aop_targets', 'AOP Targets', 'AOP Targets', NULL, '/aop_targets', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'bp_initiative', 'bp_initiative', 'Business Plan Initiatives', 'Business Plan Initiatives', NULL, '/bp_initiative', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'charged_to', 'charged_to', 'Charged To', 'Charged To', NULL, '/charged_to', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'chart_of_accounts', 'chart_of_accounts', 'Chart of Accounts', 'Chart of Accounts', NULL, '/chart_of_accounts', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'ctsr_bcr', 'ctsr_bcr', 'CTSR Budget Release Control', 'CTSR Budget Release Control', NULL, '/ctsr_bcr', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'customer_stage', 'customer_stage', 'Customer Stage', 'Customer Stage', NULL, '/customer_stage', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'estimated_return_rates', 'estimated_return_rates', 'Estimated Return Rates', 'Estimated Return Rates', NULL, '/estimated_return_rates', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'historical_return_rates', 'historical_return_rates', 'Historical Return Rates', 'Historical Return Rates', NULL, '/historical_return_rates', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'occurrence', 'occurrence', 'Occurrence', 'Occurrence', NULL, '/occurrence', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'price_list', 'price_list', 'Price List', 'Price List', NULL, '/price_list', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'target_end_user', 'target_end_user', 'Target End User', 'Target End User', NULL, '/target_end_user', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'threshold', 'threshold', 'Threshold', 'Threshold', NULL, '/threshold', '5', '1', '2', '0');
INSERT INTO `menu` (`id`, `module_name`, `name`, `controller_name`, `description`, `label_display`, `icon`, `url`, `parent`, `order_index`, `level`, `status`) VALUES (NULL, 'maintenance', 'item_master_maintenance', 'item_master_maintenance', 'Item Master Maintenance', 'Item Master Maintenance', NULL, '/item_master_maintenance', '5', '1', '2', '0');