CREATE TABLE `item_master_maintenance`(
`id` INT NOT NULL AUTO_INCREMENT,
`transaction_id` int(6) UNSIGNED ZEROFILL NOT NULL,
`short_description` INT NOT NULL,
`market_segment` VARCHAR(100) NOT NULL,
`product_segment` VARCHAR(100) NOT NULL,
`level` VARCHAR(100) NOT NULL,
`grade_level` VARCHAR(100) NOT NULL,
`track_program` VARCHAR(100) NOT NULL,
`learning_area` VARCHAR(100) NOT NULL,
`strand_discipline` VARCHAR(100) NOT NULL,
`subject_course` VARCHAR(100) NOT NULL,
`product_type` VARCHAR(100) NOT NULL,
`copyright` VARCHAR(100) NOT NULL,
`author1` VARCHAR(100) NULL,
`author2` VARCHAR(100) NULL,
`author3` VARCHAR(100) NULL,
`prod_class_disposition` VARCHAR(100) NOT NULL,
`product_format` VARCHAR(100) NOT NULL,
`pfp_scc_itemcode` VARCHAR(100) NOT NULL,
`pfp_scc_item_description` VARCHAR(100) NOT NULL,
`pfp_scc_prod_category` VARCHAR(100) NOT NULL,
`pfp_scc_prod_category2` VARCHAR(100) NOT NULL,
`pfp_tc_item_code` VARCHAR(100) NOT NULL,
`pfp_tc_item_description` VARCHAR(100) NOT NULL,
`pfp_tc_prod_category` VARCHAR(100) NOT NULL,
`pfp_tc_prod_category2` VARCHAR(100) NOT NULL,
`pfp_ec_item_code` VARCHAR(100) NOT NULL,
`pfp_ec_item_description` VARCHAR(100) NOT NULL,
`pfp_ec_prod_category` VARCHAR(100) NOT NULL,
`pfp_ec_prod_category2` VARCHAR(100) NOT NULL,
`pfnp_scc_item_code` VARCHAR(100) NOT NULL,
`pfnp_scc_item_description` VARCHAR(100) NOT NULL,
`pfnp_scc_prod_category` VARCHAR(100) NOT NULL,
`pfnp_scc_prod_category2` VARCHAR(100) NOT NULL,
`pfnp_tc_item_code` VARCHAR(100) NOT NULL,
`pfnp_tc_item_description` VARCHAR(100) NOT NULL,
`pfnp_tc_prod_category` VARCHAR(100) NOT NULL,
`pfnp_tc_prod_category2` VARCHAR(100) NOT NULL,
`pfnp_ec_item_code` VARCHAR(100) NOT NULL,
`pfnp_ec_item_description` VARCHAR(100) NOT NULL,
`pfnp_ec_prod_category` VARCHAR(100) NOT NULL,
`pfnp_ec_prod_category2` VARCHAR(100) NOT NULL,
`created_by` int(11) NOT NULL,
`date_created` timestamp NOT NULL DEFAULT current_timestamp(),
`updated_by` int(11) DEFAULT NULL,
`date_updated` datetime DEFAULT NULL,
`archived` datetime DEFAULT NULL,
PRIMARY KEY(`id`)
) ENGINE = InnoDB;
