CREATE TABLE `chart_of_accounts`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `transaction_id` int(6) UNSIGNED ZEROFILL NOT NULL,
    `account_code` INT NOT NULL,
    `description` VARCHAR(100) NOT NULL,
    `currency` VARCHAR(100) NOT NULL,
    `account_group` VARCHAR(100) NOT NULL,
    `account_classification` VARCHAR(100) NOT NULL,
    `control_account_type` VARCHAR(100) DEFAULT NULL,
    `automatic_posting_account_type` VARCHAR(100) DEFAULT NULL,
    `effective_period_from` DATE NOT NULL, 
    `effective_period_to` DATE NOT NULL,
    `consolidation_account_code` VARCHAR(100) DEFAULT NULL,
    `layout_heading` VARCHAR(100) DEFAULT NULL,
    `revised_layout_heading` VARCHAR(100) DEFAULT NULL,
    `schedule_heading` VARCHAR(100) DEFAULT NULL,
    `revised_schedule_heading` VARCHAR(100) DEFAULT NULL,
    `layout_heading_for_negative_balances` VARCHAR(100) DEFAULT NULL,
    `status` VARCHAR(100) NOT NULL,
    `activation` VARCHAR(100) NOT NULL,
    `created_by` INT(11) NOT NULL,
    `date_created` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_by` INT(11) DEFAULT NULL,
    `date_updated` DATETIME DEFAULT NULL,
    `archived` INT(11) DEFAULT NULL,
    PRIMARY KEY(`id`)
)   ENGINE = InnoDB;
